version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"  # Map port 80 of the container to port 8080 on the host
    environment:
      WORDPRESS_DB_HOST: db  # Hostname of the database service
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db  # Ensure db service is started before wordpress

  db:
    image: mysql:5.7  # Using MySQL version 5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data

volumes:
  db_data:  # Define a named volume for MySQL data persistence
